### ISSUE TITLE
Not Downloading at Max Resolution

### ISSUE THREAD

**Issue by CoreySG9** [infantdeveloper/ytks-downloader#12]
If you download a clip with a resolution of 2560x1440, the app will only download at 1920x1080. Unsure if this is the case with higher resolutions (e.g. 4k).

**Comment by infantdeveloper** [comment]
Fixed in the [newest release](https://github.com/infantdeveloper/ytks-downloader/releases/tag/1.1.12). 

Thanks for pointing out the issue!
