### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by BrillSouper** [infantdeveloper/ytks-downloader#2]
not exactly an issue but more a question as i dont see anywhere to ask questions. when you download a certain clip where does it get downloaded to so i can find it?

**Comment by infantdeveloper** [comment]
If you are downloading a single clip it will be downloaded to the same directory the .exe is in, if you're downloading a match list it creates a folder (with the same name as the match list file name) in the same directory the .exe is in and puts all downloaded clips into that folder
