### ISSUE TITLE
Video Language Not English

### ISSUE THREAD

**Issue by ghost** [infantdeveloper/ytks-downloader#3]
English will not be downloaded for videos that support multiple audio tracks. This is best shown with MrBeast's latest videos.

**Comment by infantdeveloper** [comment]
Thanks for making me aware of that!

Fixed in:
https://github.com/infantdeveloper/ytks-downloader/commit/2fc6ef274dba4c5d507fb28d485d55bb250a8af5

Download the new version here:
https://github.com/infantdeveloper/ytks-downloader/releases/tag/1.1.7
