### ISSUE TITLE
unable to download cips

### ISSUE THREAD

**Issue by wealthypotato** [infantdeveloper/ytks-downloader#4]
I seem to be getting errors when attempting to download a clip, in the terminal it states that "ERROR: Requested format not available, i was wondering if there was something i was doing wrong on my end, would love a response or update. thank you.

**Comment by infantdeveloper** [comment]
Please provide the url/match file you pasted into the downloader

**Comment by wealthypotato** [comment]
https://ytks.app/search?url=https://www.youtube.com/playlist?list=UU-lHJZR3Gqxm24_Vd_AJ5Yw&query=japan&lvid=mNHgVZPlh5g&lmt=357960

**Comment by infantdeveloper** [comment]
Thank you for reporting the issue!

Fixed in https://github.com/infantdeveloper/ytks-downloader/commit/31932ed8c8ab5d06cf2a27e97f2f2af79aff1e26
Download the fixed version here:
https://github.com/infantdeveloper/ytks-downloader/releases/tag/1.1.8

**Comment by sneakybadgrr** [comment]
I am having the same issue, it repeats requested format not available 3 times then says unable to download the clip,
the url is : https://ytks.app/search?url=https://www.youtube.com/@sneakybadger1766&query=spike&lvid=vuEu5rrlcDM&lmt=885120

**Comment by infantdeveloper** [comment]
Thank you for reporting the issue!

Fixed in https://github.com/infantdeveloper/ytks-downloader/commit/b10d5e410f972f1bf0d03d16dc6a7ca930e253d7
Download the fixed version here:
https://github.com/infantdeveloper/ytks-downloader/releases/tag/1.1.9
