### ISSUE TITLE
DLL load failed while importing QtCore

### ISSUE THREAD

**Issue by wealthypotato** [infantdeveloper/ytks-downloader#7]
Currently running python 12, i attempted to run the code when i ran into the following import error :DLL load failed while importing QtCore: The specified procedure could not be found. 

Could this be to a certain module that has not been installed or maybe the module has not been updated to the latest version of 
python? 

Thank you for your time and i await your speedy response

**Comment by infantdeveloper** [comment]
Hi @wealthypotato,

thanks for reaching out!
The issue appears to originate from the PyQt6 (specifically one of its dependencies).
I fixed it in [this commit](https://github.com/infantdeveloper/ytks-downloader/commit/11a07c1bef4dc545e16315e70b181fb1164a33f6).

Everything should work now, once you pulled from the repo again :)
